# Generated by Django 6.0.3 on 2026-04-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="coins",
            field=models.IntegerField(default=0),
        ),
    ]
