# Generated by Django 6.0.3 on 2026-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="solution_code",
            field=models.TextField(blank=True),
        ),
    ]
