# Generated by Django 6.0.3 on 2026-04-07 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("dsa", "DSA"),
                            ("database", "Database"),
                            ("aiml", "AI/ML"),
                            ("sysdesign", "System Design"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tier", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("given_code", models.TextField()),
                ("expected_output", models.TextField()),
                ("model_solution", models.TextField()),
                ("constraints", models.JSONField(default=list)),
                ("section_id", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CodeSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("score_total", models.IntegerField(default=0)),
                ("score_breakdown", models.JSONField(default=dict)),
                ("bugs_fixed", models.IntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("is_first_attempt", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="learner.gamesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(default=1)),
                ("xp_total", models.IntegerField(default=0)),
                ("lives", models.IntegerField(default=3)),
                ("coins", models.IntegerField(default=100)),
                ("streak_days", models.IntegerField(default=0)),
                ("last_submission_date", models.DateField(blank=True, null=True)),
                ("badges_earned", models.JSONField(default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamesession",
            name="learner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="learner.learnerprofile",
            ),
        ),
        migrations.CreateModel(
            name="RemediationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("dsa", "DSA"),
                            ("database", "Database"),
                            ("aiml", "AI/ML"),
                            ("sysdesign", "System Design"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("current_day", models.IntegerField(default=1)),
                ("current_phase", models.IntegerField(default=1)),
                ("phase_unlocked", models.JSONField(default=list)),
                ("weak_areas", models.JSONField(default=list)),
                ("baseline_competency", models.IntegerField(default=0)),
                ("overall_competency", models.IntegerField(default=0)),
                ("skill_snapshots", models.JSONField(default=list)),
                ("mastered", models.BooleanField(default=False)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remediation_plans",
                        to="learner.learnerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gamesession",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learner.task"
            ),
        ),
        migrations.CreateModel(
            name="TaskBug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bugs",
                        to="learner.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskHint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_questions",
                        to="learner.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DomainCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("web", "Web Development"),
                            ("dsa", "DSA"),
                            ("database", "Database"),
                            ("aiml", "AI/ML"),
                            ("sysdesign", "System Design"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tier", models.IntegerField(default=1)),
                ("xp", models.IntegerField(default=0)),
                ("competency_score", models.IntegerField(default=0)),
                (
                    "learner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="learner.learnerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("learner", "domain")},
            },
        ),
        migrations.CreateModel(
            name="RemediationDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                (
                    "phase",
                    models.IntegerField(
                        choices=[
                            (1, "Foundation"),
                            (2, "Application"),
                            (3, "Stress Test"),
                            (4, "Mastery"),
                        ],
                        default=1,
                    ),
                ),
                ("phase_name", models.CharField(default="Foundation", max_length=20)),
                ("is_checkpoint", models.BooleanField(default=False)),
                ("label", models.CharField(default="", max_length=255)),
                ("topic", models.CharField(default="", max_length=100)),
                ("section_id", models.CharField(blank=True, default="", max_length=20)),
                ("objective", models.TextField(default="")),
                ("concept_card", models.JSONField(blank=True, null=True)),
                ("exercises", models.JSONField(default=list)),
                ("resources", models.JSONField(default=list)),
                ("is_completed", models.BooleanField(default=False)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("exercises_done", models.IntegerField(default=0)),
                ("xp_base", models.IntegerField(default=100)),
                ("xp_earned", models.IntegerField(default=0)),
                ("time_estimate_min", models.IntegerField(default=16)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="learner.remediationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["day_number"],
                "unique_together": {("plan", "day_number")},
            },
        ),
    ]
